theme: jekyll-theme-minimal
title: art de la vaillance
description: I work as an independent freehand/digital artist, continuously studying, researching and progressing with interest in animating, sewing, art, and overall construction/development. Je travaille comme un artiste indépendant de freehand/digital, étudie en permanence, à rechercher et à progresser avec intérêt en animant, couture, art, and overall construction/development.
